#!/usr/bin/env python

# Copyright 2026 Rob Meades
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Protocol Generator for ESP32 Control Interface, entirely generated by DeepSeek

This script parses the C protocol header file and generates a Python module
with all the protocol definitions, message classes, and helper functions.

Usage:
    python3 generate_protocol.py <protocol.h> [output.py]
"""

import re
import sys
import struct
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Any
from dataclasses import dataclass, field

@dataclass
class ProtocolDef:
    """Container for parsed protocol definitions"""
    version: Optional[int] = None
    magic: Dict[str, int] = field(default_factory=dict)
    log_max_len: Optional[int] = None
    commands: Dict[str, int] = field(default_factory=dict)
    queries: Dict[str, int] = field(default_factory=dict)
    indications: Dict[str, int] = field(default_factory=dict)
    log_levels: Dict[str, int] = field(default_factory=dict)
    status_codes: Dict[str, int] = field(default_factory=dict)
    structs: Dict[str, Dict[str, Tuple[str, int]]] = field(default_factory=dict)


class CHeaderParser:
    """Parser for C protocol header files"""
    
    def __init__(self, header_path: str):
        self.header_path = Path(header_path)
        self.content = self.header_path.read_text()
        self.protocol = ProtocolDef()
        
    def parse(self) -> ProtocolDef:
        """Parse the C header and extract all protocol definitions"""
        self._parse_macros()
        self._parse_enums()
        self._parse_structs()
        return self.protocol
    
    def _parse_macros(self):
        """Extract #define macros"""
        # Protocol version
        version_match = re.search(r'#define\s+PROTOCOL_VERSION\s+(0x[0-9A-Fa-f]+|\d+)', self.content)
        if version_match:
            self.protocol.version = self._parse_int(version_match.group(1))
        
        # Magic bytes
        magic_pattern = r'#define\s+PROTOCOL_MAGIC_(\w+)\s+(0x[0-9A-Fa-f]+|\d+)'
        for match in re.finditer(magic_pattern, self.content):
            name = match.group(1)
            value = self._parse_int(match.group(2))
            self.protocol.magic[name] = value
        
        # Log message max length
        log_len_match = re.search(r'#define\s+LOG_MESSAGE_MAX_LEN\s+(\d+)', self.content)
        if log_len_match:
            self.protocol.log_max_len = int(log_len_match.group(1))
    
    def _parse_int(self, value_str: str) -> int:
        """Parse integer value that might be hex, decimal, or binary"""
        value_str = value_str.strip()
        
        # Handle empty string
        if not value_str:
            return 0
        
        # Handle hexadecimal
        if value_str.startswith('0x'):
            try:
                return int(value_str, 16)
            except ValueError:
                return 0
        
        # Handle binary
        if value_str.startswith('0b'):
            try:
                return int(value_str, 2)
            except ValueError:
                return 0
        
        # Handle decimal
        try:
            return int(value_str)
        except ValueError:
            return 0
    
    def _parse_enum_body(self, body: str) -> Dict[str, int]:
        """Parse an enum body and return name-value pairs"""
        values = {}
        
        # Remove comments
        body = re.sub(r'//.*$', '', body, flags=re.MULTILINE)
        
        # Split into individual lines/entries
        entries = []
        for line in body.split('\n'):
            line = line.strip()
            if line:
                # Split multiple entries on same line by comma
                for entry in line.split(','):
                    entry = entry.strip()
                    if entry:
                        entries.append(entry)
        
        # First pass: collect all explicitly defined values
        for entry in entries:
            if '=' in entry:
                name, expr = entry.split('=', 1)
                name = name.strip()
                expr = expr.strip()
                
                # Try to evaluate the expression
                try:
                    # Handle simple expressions like BASE + 1
                    if '+' in expr and not any(c in expr for c in 'xabcdef'):  # Not hex
                        parts = expr.split('+')
                        base = parts[0].strip()
                        offset = int(parts[1].strip())
                        
                        # Check if base is a reference to another enum value
                        if base in values:
                            value = values[base] + offset
                        else:
                            # Try to parse base as a number
                            try:
                                base_val = self._parse_int(base)
                                value = base_val + offset
                            except:
                                # We'll resolve this in the second pass
                                value = None
                    else:
                        # Direct value or hex
                        value = self._parse_int(expr)
                    
                    if value is not None:
                        values[name] = value
                except:
                    # We'll resolve this in the second pass
                    pass
        
        # Second pass: resolve references and assign implicit values
        last_value = -1
        for entry in entries:
            if '=' in entry:
                name, expr = entry.split('=', 1)
                name = name.strip()
                expr = expr.strip()
                
                if name not in values:
                    # This entry needs to be resolved
                    try:
                        if '+' in expr:
                            parts = expr.split('+')
                            base = parts[0].strip()
                            offset = int(parts[1].strip())
                            
                            if base in values:
                                value = values[base] + offset
                                values[name] = value
                                last_value = value
                    except:
                        pass
            else:
                # Implicitly valued entry
                name = entry
                if last_value >= 0:
                    last_value += 1
                else:
                    last_value = 0
                values[name] = last_value
        
        return values
    
    def _parse_enums(self):
        """Extract all enum definitions"""
        # Find all enum blocks
        enum_pattern = r'typedef\s+enum\s*{([^}]+)}\s*(\w+)_t;'
        
        for match in re.finditer(enum_pattern, self.content, re.DOTALL):
            enum_name = match.group(2)
            enum_body = match.group(1)
            
            values = self._parse_enum_body(enum_body)
            
            # Route to appropriate container
            if enum_name == 'cmd':
                self.protocol.commands = values
            elif enum_name == 'qry':
                self.protocol.queries = values
            elif enum_name == 'ind':
                self.protocol.indications = values
            elif enum_name == 'log_level':
                self.protocol.log_levels = values
            elif enum_name == 'status':
                self.protocol.status_codes = values
    
    def _parse_structs(self):
        """Extract struct definitions"""
        struct_pattern = r'typedef\s+struct\s+__attribute__\(\(packed\)\)\s*{([^}]+)}\s*(\w+)_t;'
        
        for match in re.finditer(struct_pattern, self.content, re.DOTALL):
            struct_name = match.group(2)
            struct_body = match.group(1)
            
            fields = self._parse_struct_body(struct_body)
            self.protocol.structs[struct_name] = fields
    
    def _parse_struct_body(self, body: str) -> Dict[str, Tuple[str, int]]:
        """Parse struct body and return field name -> (type, size) mappings"""
        fields = {}
        
        # Remove comments
        body = re.sub(r'//.*$', '', body, flags=re.MULTILINE)
        
        # Type mapping
        type_sizes = {
            'uint8_t': 1,
            'uint16_t': 2,
            'uint32_t': 4,
            'char': 1
        }
        
        for line in body.split(';'):
            line = line.strip()
            if not line:
                continue
            
            # Parse field declaration
            parts = line.split()
            if len(parts) >= 2:
                type_name = parts[0]
                field_name = parts[1].rstrip(';')
                
                # Handle arrays
                array_match = re.search(r'(\w+)\[(\d+)\]', field_name)
                if array_match:
                    field_name = array_match.group(1)
                    array_size = int(array_match.group(2))
                    element_size = type_sizes.get(type_name, 1)
                    size = element_size * array_size
                else:
                    size = type_sizes.get(type_name, 1)
                
                fields[field_name] = (type_name, size)
        
        return fields
    
def _parse_int(self, value_str: str) -> int:
    """Parse integer value that might be hex, decimal, or binary"""
    value_str = value_str.strip()
    
    # Handle empty string
    if not value_str:
        return 0
    
    # Handle hexadecimal
    if value_str.startswith('0x'):
        try:
            return int(value_str, 16)
        except ValueError:
            # If it's not a valid hex number, it might be a reference to another enum
            return 0
    
    # Handle binary
    if value_str.startswith('0b'):
        try:
            return int(value_str, 2)
        except ValueError:
            return 0
    
    # Handle decimal
    try:
        return int(value_str)
    except ValueError:
        # If it's not a number, it's probably a reference to another enum value
        # We'll handle this in the enum parsing by looking up references
        return 0

class PythonGenerator:
    """Generate Python module from parsed protocol definitions"""
    
    def __init__(self, protocol: ProtocolDef):
        self.p = protocol
        self.output = []
    
    def generate(self) -> str:
        """Generate the complete Python module"""
        self._add_header()
        self._add_imports()
        self._add_constants()
        self._add_enums()
        self._add_message_classes()
        self._add_helper_functions()
        
        return '\n'.join(self.output)
    
    def _add_header(self):
        """Add module header and docstring"""
        self.output.extend([
            '#!/usr/bin/env python3',
            '"""',
            'Auto-generated protocol definitions for ESP32 control interface.',
            '',
            'This module is generated from the C protocol header file.',
            'Do not edit this file directly - edit the .h file and regenerate.',
            '"""',
            ''
        ])
    
    def _add_imports(self):
        """Add required imports"""
        self.output.extend([
            'import struct',
            'from enum import IntEnum',
            'from typing import Optional, Union, Tuple, Any',
            'import socket',
            ''
        ])
    
    def _add_constants(self):
        """Add protocol constants"""
        if self.p.version is not None:
            self.output.append(f'PROTOCOL_VERSION = {self.p.version}')
        
        if self.p.magic:
            self.output.append('\n# Magic bytes')
            for name, value in sorted(self.p.magic.items()):
                self.output.append(f'PROTOCOL_MAGIC_{name} = {value}')
        
        if self.p.log_max_len is not None:
            self.output.append(f'\nLOG_MESSAGE_MAX_LEN = {self.p.log_max_len}')
        
        self.output.append('')
    
    def _add_enums(self):
        """Add enum classes"""
        enum_configs = [
            ('Cmd', self.p.commands, 'Command codes'),
            ('Qry', self.p.queries, 'Query codes'),
            ('Ind', self.p.indications, 'Indication codes'),
            ('LogLevel', self.p.log_levels, 'Log levels'),
            ('Status', self.p.status_codes, 'Status codes')
        ]
        
        for enum_name, values, description in enum_configs:
            if values:
                self.output.extend([
                    f'class {enum_name}(IntEnum):',
                    f'    """{description}"""'
                ])
                
                # Sort by value for consistent output
                for name, value in sorted(values.items(), key=lambda x: x[1]):
                    # Clean up enum names (remove prefixes if desired)
                    clean_name = name
                    if enum_name == 'Cmd' and name.startswith('CMD_'):
                        clean_name = name[4:]
                    elif enum_name == 'Qry' and name.startswith('QRY_'):
                        clean_name = name[4:]
                    elif enum_name == 'Ind' and name.startswith('IND_'):
                        clean_name = name[4:]
                    
                    self.output.append(f'    {clean_name} = {value}')
                
                self.output.append('')
    
    def _get_struct_format(self, struct_name: str) -> Tuple[str, int]:
        """Get struct format string and size"""
        if struct_name not in self.p.structs:
            return None, 0
        
        struct_info = self.p.structs[struct_name]
        format_chars = []
        
        # Type to struct format mapping
        type_format = {
            'uint8_t': 'B',
            'uint16_t': 'H',
            'uint32_t': 'I',
            'char': 's'
        }
        
        for field, (type_name, size) in struct_info.items():
            if type_name == 'char' and size > 1:
                format_chars.append(f'{size}s')
            else:
                format_chars.append(type_format.get(type_name, 'B'))
        
        format_str = '<' + ''.join(format_chars)  # Little-endian
        total_size = struct.calcsize(format_str)
        
        return format_str, total_size
    
    def _add_message_classes(self):
        """Add message class definitions"""
        # Map struct names to message class names and magic constants
        message_types = [
            ('cmd_msg_t', 'CmdMsg', 'COMMAND', ['command', 'param']),
            ('rsp_msg_t', 'RspMsg', 'RESPONSE', ['status', 'value']),
            ('ind_msg_t', 'IndMsg', 'IND', ['ind', 'value']),
            ('log_msg_t', 'LogMsg', 'LOG', ['level', 'message'])
        ]
        
        for struct_name, class_name, magic_name, fields in message_types:
            if struct_name in self.p.structs:
                self._generate_message_class(struct_name, class_name, magic_name, fields)
    
    def _generate_message_class(self, struct_name: str, class_name: str, 
                               magic_name: str, fields: List[str]):
        """Generate a specific message class"""
        format_str, total_size = self._get_struct_format(struct_name)
        if format_str is None:
            return
        
        magic_value = self.p.magic.get(magic_name, 0)
        
        self.output.extend([
            f'class {class_name}:',
            f'    """{class_name} - packed binary message"""',
            f'    FORMAT = "{format_str}"',
            f'    SIZE = {total_size}',
            f'    MAGIC = PROTOCOL_MAGIC_{magic_name}',
            '',
            f'    def __init__(self, {fields[0]}, {fields[1]}=0):',
            f'        self.magic = self.MAGIC',
            f'        self.{fields[0]} = {fields[0]}',
            f'        self.{fields[1]} = {fields[1]}',
            '',
            '    def pack(self) -> bytes:',
            '        """Pack message into bytes for transmission"""',
            f'        return struct.pack(self.FORMAT,',
            f'                          self.magic,',
            f'                          self.{fields[0]},',
            f'                          self.{fields[1]})',
            '',
            '    @classmethod',
            f'    def unpack(cls, data: bytes) -> "{class_name}":',
            '        """Unpack bytes into a message instance"""',
            '        if len(data) != cls.SIZE:',
            '            raise ValueError(f"Invalid message size: got {len(data)}, expected {cls.SIZE}")',
            '        values = struct.unpack(cls.FORMAT, data)',
            '        magic = values[0]',
            '        if magic != cls.MAGIC:',
            '            raise ValueError(f"Invalid magic byte: got {magic:#x}, expected {cls.MAGIC:#x}")',
            f'        return cls(values[1], values[2])',
            '',
            '    def __repr__(self):',
            f' return f"<{class_name} {fields[0]}={{self.{fields[0]}}}, {fields[1]}={{self.{fields[1]}}}>"',
            ''
        ])
    
    def _add_helper_functions(self):
        """Add utility functions for working with the protocol"""
        self.output.extend([
            'def send_message(sock: socket.socket, msg) -> bool:',
            '    """Send a protocol message over a socket"""',
            '    try:',
            '        data = msg.pack()',
            '        sock.sendall(data)',
            '        return True',
            '    except Exception as e:',
            '        print(f"Error sending message: {e}")',
            '        return False',
            '',
            'def receive_message(sock: socket.socket, msg_class, timeout: Optional[float] = None):',
            '    """Receive and unpack a specific message type"""',
            '    original_timeout = sock.gettimeout()',
            '    try:',
            '        if timeout is not None:',
            '            sock.settimeout(timeout)',
            '        data = sock.recv(msg_class.SIZE)',
            '        if len(data) == 0:',
            '            return None  # Connection closed',
            '        return msg_class.unpack(data)',
            '    except socket.timeout:',
            '        return None',
            '    except Exception as e:',
            '        print(f"Error receiving message: {e}")',
            '        return None',
            '    finally:',
            '        sock.settimeout(original_timeout)',
            ''
        ])
    def print_usage_instructions(self):
        """Print usage instructions for the generated module"""
        instructions = f"""
╔════════════════════════════════════════════════════════════════════════════╗
║                    Protocol Module Generated Successfully                  ║
╚════════════════════════════════════════════════════════════════════════════╝

The Python protocol module has been generated. Here's how to use it:

📦 IMPORTING
────────────────────────────────────────────────────────────────────────────
    from protocol import (
        # Enums
        Command, Query, Indication, LogLevel, Status,
        # Message classes
        CmdMsg, RspMsg, IndMsg, LogMsg,
        # Helper functions
        send_message, receive_message,
        # Constants
        PROTOCOL_VERSION, LOG_MESSAGE_MAX_LEN
    )

🎯 SENDING COMMANDS
────────────────────────────────────────────────────────────────────────────
    # Create a command (rotate clockwise)
    cmd = CmdMsg(Command.ROTATE_CLOCKWISE, param=-1)
    
    # Send over socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(('10.10.3.10', 5000))
    send_message(sock, cmd)

📥 RECEIVING RESPONSES
────────────────────────────────────────────────────────────────────────────
    # Wait for response (5 second timeout)
    rsp = receive_message(sock, RspMsg, timeout=5.0)
    if rsp:
        if rsp.status == Status.OK:
            print(f"Success! Value: {{rsp.value}}")
        else:
            print(f"Error: {{Status(rsp.status).name}}")

🔔 HANDLING INDICATIONS
────────────────────────────────────────────────────────────────────────────
    # Receive an asynchronous indication
    ind = receive_message(sock, IndMsg)
    if ind:
        print(f"Indication: {{Indication(ind.ind).name}}, value: {{ind.value}}")

📝 SENDING LOGS
────────────────────────────────────────────────────────────────────────────
    # Send a log message
    log = LogMsg(LogLevel.INFO, "System initialized")
    send_message(log_sock, log)

🔍 ENUM VALUES
────────────────────────────────────────────────────────────────────────────
    # All protocol values are available as enums
    cmd = CmdMsg(Command.LIFT_UP)                    # 0x2000
    qry = Query.LIFT_STATE                           # 0x2100  
    ind = Indication.LIFT_SENSOR_TRIGGERED_LIMIT     # 0x2201
    lvl = LogLevel.WARN                              # 0x02
    err = Status.ERROR_INVALID_PARAM                 # 0x0003

📋 MESSAGE STRUCTURES
────────────────────────────────────────────────────────────────────────────
    CmdMsg: magic(1) + command(2) + param(4) = 7 bytes
    RspMsg: magic(1) + status(2) + value(4) = 7 bytes
    IndMsg: magic(1) + ind(2) + value(4)    = 7 bytes
    LogMsg: magic(1) + level(1) + message({{LOG_MESSAGE_MAX_LEN}}) = {{LOG_MESSAGE_MAX_LEN+2}} bytes

🔄 COMPLETE EXAMPLE
────────────────────────────────────────────────────────────────────────────
    import socket
    from protocol import *
    
    # Connect to ESP32
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(('10.10.3.10', 5000))
    
    # Send command and get response
    cmd = CmdMsg(Command.ROTATE_CLOCKWISE, -1)
    if send_message(sock, cmd):
        response = receive_message(sock, RspMsg, timeout=2.0)
        if response and response.status == Status.OK:
            print("Motor rotated successfully")
    
    sock.close()

⚠️ NOTES
────────────────────────────────────────────────────────────────────────────
    • All multi-byte fields are little-endian (matches ESP32 and Raspberry Pi)
    • TCP provides reliable delivery - no checksums needed
    • Message sizes are fixed - receive exactly SIZE bytes
    • Timeout parameter is optional for receive_message()
    • The module is auto-generated - do not edit directly

For more details, see the protocol definition in the original C header file.
"""
        print(instructions)

def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python3 generate_protocol.py <protocol.h> [output.py]")
        sys.exit(1)
    
    header_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else 'protocol.py'
    
    print(f"Parsing {header_path}...")
    parser = CHeaderParser(header_path)
    protocol = parser.parse()
    
    print(f"Found:")
    print(f"  - {len(protocol.magic)} magic bytes")
    print(f"  - {len(protocol.commands)} commands")
    print(f"  - {len(protocol.queries)} queries")
    print(f"  - {len(protocol.indications)} indications")
    print(f"  - {len(protocol.log_levels)} log levels")
    print(f"  - {len(protocol.status_codes)} status codes")
    print(f"  - {len(protocol.structs)} structs")
    
    print(f"\nGenerating {output_path}...")
    generator = PythonGenerator(protocol)
    python_code = generator.generate()
    
    Path(output_path).write_text(python_code)
    # Print usage instructions
    generator.print_usage_instructions()

    print("Done!")

if __name__ == "__main__":
    main()
