#!/usr/bin/env python3
"""
Auto-generated protocol definitions for ESP32 control interface.

This module is generated from the C protocol header file.
Do not edit this file directly - edit the .h file and regenerate.
"""

import struct
from enum import IntEnum
from typing import Optional, Union, Tuple, Any
import socket

PROTOCOL_VERSION = 1

# Magic bytes
PROTOCOL_MAGIC_CMD = 170
PROTOCOL_MAGIC_IND = 204
PROTOCOL_MAGIC_LOG = 221
PROTOCOL_MAGIC_RSP = 187

LOG_MESSAGE_MAX_LEN = 256

class Cmd(IntEnum):
    """Command codes"""
    SYSTEM_BEGIN = 0
    REBOOT = 0
    STAND_ROTATE_CLOCKWISE = 0
    LIFT_UP = 0
    PLINKY_PLONKY_PLAY_START = 0
    DOOR_OPEN = 0
    LOG_START = 1
    LOG_STOP = 2
    STAND_BEGIN = 4096
    STAND_ROTATE_ANTICLOCKWISE = 4097
    LIFT_BEGIN = 8192
    LIFT_DOWN = 8193
    PLINKY_PLONKY_BEGIN = 12288
    PLINKY_PLONKY_PLAY_STOP = 12289
    DOOR_BEGIN = 16384
    DOOR_CLOSE = 16385

class Qry(IntEnum):
    """Query codes"""
    STAND_ROTATION_STATE = 0
    LIFT_STATE = 0
    PLINKY_PLONKY_STATE = 0
    DOOR_STATE = 0
    SYSTEM_BEGIN = 256
    STAND_BEGIN = 4352
    LIFT_BEGIN = 8448
    LIFT_SENSOR_LIMIT = 8449
    PLINKY_PLONKY_BEGIN = 12544
    PLINKY_PLONKY_SENSOR_REFERENCE = 12545
    DOOR_BEGIN = 16640
    DOOR_SENSOR_OPEN = 16641

class Ind(IntEnum):
    """Indication codes"""
    LIFT_SENSOR_TRIGGERED_LIFT_DOWN = 0
    PLINKY_PLONKY_SENSOR_TRIGGERED_REFERENCE = 0
    DOOR_SENSOR_TRIGGERED_DOOR_OPEN = 0
    SYSTEM_BEGIN = 512
    STAND_BEGIN = 4608
    LIFT_BEGIN = 8704
    LIFT_SENSOR_TRIGGERED_LIFT_LIMIT = 8705
    PLINKY_PLONKY_BEGIN = 12800
    DOOR_BEGIN = 16896

class LogLevel(IntEnum):
    """Log levels"""
    LOG_DEBUG = 0
    LOG_INFO = 1
    LOG_WARN = 2
    LOG_ERROR = 3

class Status(IntEnum):
    """Status codes"""
    STATUS_OK = 0
    STATUS_ERROR_GENERIC = 1
    STATUS_ERROR_INVALID_COMMAND = 2
    STATUS_ERROR_INVALID_PARAM = 3
    STATUS_ERROR_BUSY = 4
    STATUS_ERROR_TIMEOUT = 5

def send_message(sock: socket.socket, msg) -> bool:
    """Send a protocol message over a socket"""
    try:
        data = msg.pack()
        sock.sendall(data)
        return True
    except Exception as e:
        print(f"Error sending message: {e}")
        return False

def receive_message(sock: socket.socket, msg_class, timeout: Optional[float] = None):
    """Receive and unpack a specific message type"""
    original_timeout = sock.gettimeout()
    try:
        if timeout is not None:
            sock.settimeout(timeout)
        data = sock.recv(msg_class.SIZE)
        if len(data) == 0:
            return None  # Connection closed
        return msg_class.unpack(data)
    except socket.timeout:
        return None
    except Exception as e:
        print(f"Error receiving message: {e}")
        return None
    finally:
        sock.settimeout(original_timeout)
