#!/usr/bin/env python3
"""
Auto-generated protocol definitions for ESP32 control interface.

This module is generated from the C protocol header file.
Do not edit this file directly - edit the .h file and regenerate.
"""

import struct
from enum import IntEnum
from typing import Optional, Union, Tuple, Any
import socket

PROTOCOL_VERSION = 1

# Magic bytes
PROTOCOL_MAGIC_CMD = 170
PROTOCOL_MAGIC_IND = 221
PROTOCOL_MAGIC_LOG = 238
PROTOCOL_MAGIC_QRY = 187
PROTOCOL_MAGIC_RSP = 204

LOG_MESSAGE_MAX_LEN = 256

class State(IntEnum):
    """States"""
    STATE_NULL = 0
    STATE_STAND_BEGIN = 4096
    STATE_STAND_STOPPED = 4096
    STATE_STAND_ROTATING_CLOCKWISE = 4097
    STATE_STAND_ROTATING_ANTICLOCKWISE = 4098
    STATE_STAND_END = 8191
    STATE_LIFT_BEGIN = 8192
    STATE_LIFT_STOPPED_UNKNOWN = 8192
    STATE_LIFT_STOPPED_DOWN = 8193
    STATE_LIFT_STOPPED_UP = 8194
    STATE_LIFT_RISING = 8195
    STATE_LIFT_LOWERING = 8196
    STATE_LIFT_END = 12287
    STATE_PLINKY_PLONKY_BEGIN = 12288
    STATE_PLINKY_PLONKY_STOPPED_UNKNOWN = 12288
    STATE_PLINKY_PLONKY_STOPPED_AT_REFERENCE = 12289
    STATE_PLINKY_PLONKY_PLAYING = 12290
    STATE_PLINKY_PLONKY_END = 16383
    STATE_DOOR_BEGIN = 16384
    STATE_DOOR_STOPPED_UNKNOWN = 16384
    STATE_DOOR_STOPPED_CLOSED = 16385
    STATE_DOOR_STOPPED_OPEN = 16386
    STATE_DOOR_OPENING = 16387
    STATE_DOOR_CLOSING = 16388
    STATE_DOOR_END = 20479

class Cmd(IntEnum):
    """Command codes"""
    CMD_SYSTEM_BEGIN = 0
    CMD_REBOOT = 0
    CMD_LOG_START = 1
    CMD_LOG_STOP = 2
    CMD_STEPPER_TARGET_START = 3
    CMD_SYSTEM_END = 255
    CMD_STAND_BEGIN = 4096
    CMD_STAND_INIT = 4096
    CMD_STAND_END = 4351
    CMD_LIFT_BEGIN = 8192
    CMD_LIFT_INIT = 8192
    CMD_LIFT_END = 8447
    CMD_PLINKY_PLONKY_BEGIN = 12288
    CMD_PLINKY_PLONKY_INIT = 12288
    CMD_PLINKY_PLONKY_END = 12543
    CMD_DOOR_BEGIN = 16384
    CMD_DOOR_INIT = 16384
    CMD_DOOR_END = 16639

class Qry(IntEnum):
    """Query codes"""
    QRY_SYSTEM_BEGIN = 256
    QRY_SYSTEM_STEPPER_STATE = 256
    QRY_SYSTEM_END = 511
    QRY_STAND_BEGIN = 4352
    QRY_STAND_END = 4607
    QRY_LIFT_BEGIN = 8448
    QRY_LIFT_SENSOR_DOWN = 8448
    QRY_LIFT_SENSOR_LIMIT = 8449
    QRY_LIFT_END = 8703
    QRY_PLINKY_PLONKY_BEGIN = 12544
    QRY_PLINKY_PLONKY_SENSOR_REFERENCE = 12544
    QRY_PLINKY_PLONKY_END = 12799
    QRY_DOOR_BEGIN = 16640
    QRY_DOOR_SENSOR_OPEN = 16640
    QRY_DOOR_END = 16895

class Ind(IntEnum):
    """Indication/Event codes"""
    IND_SYSTEM_BEGIN = 512
    IND_SYSTEM_STEPPER_TARGET_END = 512
    IND_SYSTEM_END = 767
    IND_STAND_BEGIN = 4608
    IND_STAND_END = 4863
    IND_LIFT_BEGIN = 8704
    IND_LIFT_SENSOR_TRIGGERED_LIFT_DOWN = 8704
    IND_LIFT_SENSOR_TRIGGERED_LIFT_LIMIT = 8705
    IND_LIFT_END = 8959
    IND_PLINKY_PLONKY_BEGIN = 12800
    IND_PLINKY_PLONKY_SENSOR_TRIGGERED_REFERENCE = 12800
    IND_PLINKY_PLONKY_END = 13055
    IND_DOOR_BEGIN = 16896
    IND_DOOR_SENSOR_TRIGGERED_DOOR_OPEN = 16896
    IND_DOOR_END = 17151

class LogLevel(IntEnum):
    """Log levels"""
    LOG_DEBUG = 0
    LOG_INFO = 1
    LOG_WARN = 2
    LOG_ERROR = 3

class Status(IntEnum):
    """Status codes"""
    STATUS_OK = 0
    STATUS_ERROR_GENERIC = 1
    STATUS_ERROR_INVALID_COMMAND = 2
    STATUS_ERROR_UNHANDLED_COMMAND = 3
    STATUS_ERROR_INVALID_QUERY = 4
    STATUS_ERROR_UNHANDLED_QUERY = 5
    STATUS_ERROR_INVALID_PARAM = 6
    STATUS_ERROR_ABORT = 7
    STATUS_ERROR_BUSY = 8
    STATUS_ERROR_TIMEOUT = 9
    STATUS_ERROR_HARDWARE = 10

class CmdMsg:
    """CmdMsg - packed binary message"""
    FORMAT = "<BHBiiii"
    SIZE = 20
    MAGIC = PROTOCOL_MAGIC_CMD

    def __init__(self, command, reference=0, param_1=0, param_2=0, param_3=0, param_4=0):
        self.magic = self.MAGIC
        self.command = command
        self.reference = reference
        self.param_1 = param_1
        self.param_2 = param_2
        self.param_3 = param_3
        self.param_4 = param_4

    def pack(self) -> bytes:
        """Pack message into bytes for transmission"""
        return struct.pack(self.FORMAT,
                          self.magic, self.command, self.reference, self.param_1, self.param_2, self.param_3, self.param_4)

    @classmethod
    def unpack(cls, data: bytes) -> "CmdMsg":
        """Unpack bytes into a message instance"""
        if len(data) != cls.SIZE:
            raise ValueError(f"Invalid message size: got {len(data)}, expected {cls.SIZE}")
        values = struct.unpack(cls.FORMAT, data)
        magic = values[0]
        if magic != cls.MAGIC:
            raise ValueError(f"Invalid magic byte: got {magic:#x}, expected {cls.MAGIC:#x}")
        return cls(*values[1:])

    def __repr__(self):
        return f"<CmdMsg command={self.command} reference={self.reference} param_1={self.param_1} param_2={self.param_2} param_3={self.param_3} param_4={self.param_4}>"

class QryMsg:
    """QryMsg - packed binary message"""
    FORMAT = "<BHB"
    SIZE = 4
    MAGIC = PROTOCOL_MAGIC_QRY

    def __init__(self, query, reference=0):
        self.magic = self.MAGIC
        self.query = query
        self.reference = reference

    def pack(self) -> bytes:
        """Pack message into bytes for transmission"""
        return struct.pack(self.FORMAT,
                          self.magic, self.query, self.reference)

    @classmethod
    def unpack(cls, data: bytes) -> "QryMsg":
        """Unpack bytes into a message instance"""
        if len(data) != cls.SIZE:
            raise ValueError(f"Invalid message size: got {len(data)}, expected {cls.SIZE}")
        values = struct.unpack(cls.FORMAT, data)
        magic = values[0]
        if magic != cls.MAGIC:
            raise ValueError(f"Invalid magic byte: got {magic:#x}, expected {cls.MAGIC:#x}")
        return cls(*values[1:])

    def __repr__(self):
        return f"<QryMsg query={self.query} reference={self.reference}>"

class RspMsg:
    """RspMsg - packed binary message"""
    FORMAT = "<BHBHi"
    SIZE = 10
    MAGIC = PROTOCOL_MAGIC_RSP

    def __init__(self, cmd_or_qry, reference=0, status=0, value=0):
        self.magic = self.MAGIC
        self.cmd_or_qry = cmd_or_qry
        self.reference = reference
        self.status = status
        self.value = value

    def pack(self) -> bytes:
        """Pack message into bytes for transmission"""
        return struct.pack(self.FORMAT,
                          self.magic, self.cmd_or_qry, self.reference, self.status, self.value)

    @classmethod
    def unpack(cls, data: bytes) -> "RspMsg":
        """Unpack bytes into a message instance"""
        if len(data) != cls.SIZE:
            raise ValueError(f"Invalid message size: got {len(data)}, expected {cls.SIZE}")
        values = struct.unpack(cls.FORMAT, data)
        magic = values[0]
        if magic != cls.MAGIC:
            raise ValueError(f"Invalid magic byte: got {magic:#x}, expected {cls.MAGIC:#x}")
        return cls(*values[1:])

    def __repr__(self):
        return f"<RspMsg cmd_or_qry={self.cmd_or_qry} reference={self.reference} status={self.status} value={self.value}>"

class IndMsg:
    """IndMsg - packed binary message"""
    FORMAT = "<BHi"
    SIZE = 7
    MAGIC = PROTOCOL_MAGIC_IND

    def __init__(self, ind, value=0):
        self.magic = self.MAGIC
        self.ind = ind
        self.value = value

    def pack(self) -> bytes:
        """Pack message into bytes for transmission"""
        return struct.pack(self.FORMAT,
                          self.magic, self.ind, self.value)

    @classmethod
    def unpack(cls, data: bytes) -> "IndMsg":
        """Unpack bytes into a message instance"""
        if len(data) != cls.SIZE:
            raise ValueError(f"Invalid message size: got {len(data)}, expected {cls.SIZE}")
        values = struct.unpack(cls.FORMAT, data)
        magic = values[0]
        if magic != cls.MAGIC:
            raise ValueError(f"Invalid magic byte: got {magic:#x}, expected {cls.MAGIC:#x}")
        return cls(*values[1:])

    def __repr__(self):
        return f"<IndMsg ind={self.ind} value={self.value}>"

class LogMsg:
    """LogMsg - packed binary message"""
    FORMAT = f"<BB {LOG_MESSAGE_MAX_LEN}s"
    SIZE = 2 + LOG_MESSAGE_MAX_LEN
    MAGIC = PROTOCOL_MAGIC_LOG

    def __init__(self, level, message=""):
        self.magic = self.MAGIC
        self.level = level
        self.message = message

    def pack(self) -> bytes:
        """Pack message into bytes for transmission"""
        # Truncate message if too long
        msg_bytes = self.message.encode("utf-8")[:LOG_MESSAGE_MAX_LEN-1]
        # Pad with null bytes to reach full size
        padded = msg_bytes + b"\0" * (LOG_MESSAGE_MAX_LEN - len(msg_bytes))
        return struct.pack(self.FORMAT,
                          self.magic,
                          self.level,
                          padded)

    @classmethod
    def unpack(cls, data: bytes) -> "LogMsg":
        """Unpack bytes into a message instance"""
        if len(data) != cls.SIZE:
            raise ValueError(f"Invalid message size: got {len(data)}, expected {cls.SIZE}")
        magic, level, msg_bytes = struct.unpack(cls.FORMAT, data)
        if magic != cls.MAGIC:
            raise ValueError(f"Invalid magic byte: got {magic:#x}, expected {cls.MAGIC:#x}")
        # Decode null-terminated string
        message = msg_bytes.split(b"\0", 1)[0].decode("utf-8")
        return cls(level, message)

    def __repr__(self):
        return f"<LogMsg level={self.level}, message=\"{self.message}\">"

def send_message(sock: socket.socket, msg) -> bool:
    """Send a protocol message over a socket"""
    try:
        data = msg.pack()
        sock.sendall(data)
        return True
    except Exception as e:
        print(f"Error sending message: {e}")
        return False

def receive_message(sock: socket.socket, msg_class, timeout: Optional[float] = None):
    """Receive and unpack a specific message type"""
    original_timeout = sock.gettimeout()
    try:
        if timeout is not None:
            sock.settimeout(timeout)
        data = sock.recv(msg_class.SIZE)
        if len(data) == 0:
            return None  # Connection closed
        return msg_class.unpack(data)
    except socket.timeout:
        return None
    except Exception as e:
        print(f"Error receiving message: {e}")
        return None
    finally:
        sock.settimeout(original_timeout)
